### ISSUE TITLE
Ask students to install Ubuntu?

### ISSUE THREAD

**Issue by besarthoxhaj** [gazaskygeeks/bootcamp#4]
@abdullah-abunada @MostafaBalata what do you think?

Do you have any experience installing Ubuntu?

https://www.ubuntu.com/download/desktop

http://www.everydaylinuxuser.com/2015/11/how-to-install-ubuntu-linux-alongside.html

Students will be asked to use always the command line - for git and for potentially writing some bash scripts. Having a windows environment will not help.

**Comment by besarthoxhaj** [comment]
I also asked @Walidmash to install Ubuntu on his computer. After that, he can help the students do the same.

**Comment by abdullah-abunada** [comment]
Hi Besart,
yes I have experience to work on Ubuntu as a Server and Desktop OS
